#!/bin/sh

root -l -b -q 'fig_syst_v1even_eta_trckqual.C()'
root -l -b -q 'fig_syst_v1even_eta_vtxcut.C()'
root -l -b -q 'fig_syst_v1even_pt_trckqual.C()'
root -l -b -q 'fig_syst_v1even_pt_vtxcut.C()'
root -l -b -q 'fig_syst_v1odd_eta_trckqual.C()'
root -l -b -q 'fig_syst_v1odd_eta_vtxcut.C()'
root -l -b -q 'fig_syst_v1odd_pt_trkqual.C()'
root -l -b -q 'fig_syst_v1odd_pt_vtx.C()'
root -l -b -q 'fig_syst_fits.C'

root -l -b -q 'fig_syst_decor_v1even_eta_trckqual.C()'
root -l -b -q 'fig_syst_decor_v1even_eta_vtxcut.C()'
root -l -b -q 'fig_syst_decor_v1even_pt_trckqual.C()'
root -l -b -q 'fig_syst_decor_v1even_pt_vtxcut.C()'
root -l -b -q 'fig_syst_decor_v1odd_eta_trckqual.C()'
root -l -b -q 'fig_syst_decor_v1odd_eta_vtxcut.C()'
root -l -b -q 'fig_syst_decor_v1odd_pt_trkqual.C()'
root -l -b -q 'fig_syst_decor_v1odd_pt_vtx.C()'
root -l -b -q 'fig_syst_decor_fits.C'
